# Generated by Django 3.2.9 on 2022-01-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='address_line_2',
        ),
    ]
