# Generated by Django 3.2.9 on 2022-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20220103_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['code'], 'verbose_name': 'Catégorie'},
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
    ]
