# Generated by Django 3.2.9 on 2022-01-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20220103_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='phone',
        ),
    ]
