# Generated by Django 3.2.9 on 2022-01-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0009_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=300, upload_to='category'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50, null=True, verbose_name='Modèle')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Constructeur')),
                ('registration_number', models.CharField(max_length=9, unique=True, verbose_name='Immatriculation')),
                ('vehicle_identification_number', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor.agency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor.category')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'ordering': ['manufacturer', 'car_model', 'registration_number'],
            },
        ),
    ]
