# Generated by Django 3.2.9 on 2022-01-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_auto_20220103_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['category', 'manufacturer', 'car_model', 'registration_number', 'agency'], 'verbose_name': 'Véhicule'},
        ),
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=30, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sample',
            field=models.CharField(max_length=30, verbose_name='Modèle principal'),
        ),
    ]
