# Generated by Django 3.2.9 on 2022-01-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='creditCardValidity',
            field=models.DateField(verbose_name='Fin de validité de la carte de paiement'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('scheduled_date_end', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor.agency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor.vehicle')),
            ],
        ),
    ]
