# Generated by Django 3.2.9 on 2022-01-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0014_auto_20220104_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='agence',
            new_name='agency',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_end',
            field=models.DateTimeField(verbose_name='Date de fin de location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_start',
            field=models.DateTimeField(verbose_name='Date de début de location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date_end',
            field=models.DateTimeField(verbose_name='Date prévue de fin de location'),
        ),
    ]
