# Generated by Django 3.2.8 on 2022-01-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_auto_20220107_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creditCardNumber',
            field=models.CharField(max_length=16, null=True, verbose_name='Numéro de carte de paiement'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creditCardValidity',
            field=models.DateField(null=True, verbose_name='Fin de validité de la carte de paiement'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='licence_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Numéro du permis de conduire'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='licence_scan',
            field=models.ImageField(blank=True, upload_to='customer_licences', verbose_name='Copie permis de conduire'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(max_length=5, null=True, verbose_name='Code postal'),
        ),
    ]
