# Generated by Django 3.2.9 on 2022-01-11 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0016_auto_20220107_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Agences de location'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['code'], 'verbose_name': 'Catégories de véhicule'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Immatriculation invalide ! Le format attendu est AA-000-AA.', regex='^[a-zA-Z]{2}-\\d{3}-[a-zA-Z]{2}$')], verbose_name='Immatriculation'),
        ),
    ]
