# Generated by Django 3.2.9 on 2022-01-12 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0017_auto_20220111_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='scheduled_date_end',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Immatriculation invalide ! Le format attendu est AA-000-AA.', regex='^[A-Z]{2}-\\d{3}-[A-Z]{2}$')], verbose_name='Immatriculation'),
        ),
    ]
